<a href="https://colab.research.google.com/github/ybchoe/python_programming/blob/main/hw9/python_numpy_20230517.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://numpy.org/doc/stable/user/absolute_beginners.html

In [ ]:
import numpy as np

In [ ]:
a=np.arange(6)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[0]

0

In [ ]:
a[1]

1

In [ ]:
a[:]  #행과 열을 구분. 1차원

array([0, 1, 2, 3, 4, 5])

In [ ]:
a2=a[np.newaxis,:]  #새로운 차원을 만듬. 2차원

In [ ]:
a2.shape

(1, 6)

In [ ]:
a.shape

(6,)

In [ ]:
a=[0,1,2,3,4,5,6]

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6]

In [ ]:
type(a)

list

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,1]

2

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
a=np.array([1, 2, 3])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.empty(2)

array([0., 0.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a=1.

In [ ]:
a

1.0

In [ ]:
type(a)

float

In [ ]:
x=np.ones(2, dtype=np.int64)

In [ ]:
x

array([1, 1], dtype=int64)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a= np.sort(arr) #내림, 오름차순 가능

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [ ]:
a = np.concatenate((x,y), axis=0)

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])

In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
np.reshape(a, newshape=(1,6), order='c')

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.shape

(6,)

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
a[1][1]

5

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a2=a[np.newaxis,:]

In [ ]:
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, : ]

In [ ]:
row_vector.shape

(1, 6)

In [ ]:
row_vector = a[:, np.newaxis]

In [ ]:
row_vector.shape

(6, 1)

In [ ]:
row_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [ ]:
c

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
data = np.array([1,2,3])

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[0]

1

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
b=2

In [ ]:
if b >5:
    print("에구 너무 큰데요")
else:
    print("좋아요")

좋아요


In [ ]:
b>5

False

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[a<5]

array([1, 2, 3, 4])

In [ ]:
a[a>=3]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
(a>2)&(a<11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [ ]:
a[(a>5)|(a==11)]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b=np.nonzero(a<5)

In [ ]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [ ]:
list_of_coordinates=list(zip(b[0],b[1]))

In [ ]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [ ]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr1=a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1=np.array([[1,1],[2,2]])

In [ ]:
a2=np.array([[3,3],[4,4]])

In [ ]:
a1

array([[1, 1],
       [2, 2]])

In [ ]:
a2

array([[3, 3],
       [4, 4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.concatenate((a1,a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
a=np.arange(1,15)

In [ ]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
np.hsplit(x,(3,6,8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2,3]

12

In [ ]:
a[2,:]

array([ 9, 10, 11, 12])

In [ ]:
a[:,2]

array([ 3,  7, 11])

In [ ]:
b1=a[0,:]

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0]=99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b1=a[0,:].copy()

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0]=99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
data=np.array([1,2])

In [ ]:
ones=np.ones(2, dtype=int)

In [ ]:
data

array([1, 2])

In [ ]:
ones

array([1, 1])

In [ ]:
data+ones

array([2, 3])

In [ ]:
data-ones

array([0, 1])

In [ ]:
data*ones

array([1, 2])

In [ ]:
data/ones

array([1., 2.])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b=[1,2,3,4]

In [ ]:
len(b)

4

In [ ]:
b.sort()

In [ ]:
b

[1, 2, 3, 4]

In [ ]:
b=np.array([[1,1],[2,2]])

In [ ]:
b.sum()

6

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data=np.array([1.0,2.0])

In [ ]:
data*1.6

array([1.6, 3.2])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.max()

4

In [ ]:
a.min()

1

In [ ]:
a.sum()

10

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b = np.array([[1, 4],[2, 7]])

In [ ]:
b.min(axis=0)  #행을 기준으로

array([1, 4])

In [ ]:
b.max()

7

In [ ]:
b.sum()

14

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data[0,1]

2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2,0]

array([1, 3])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 4, 6])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

In [ ]:
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

In [ ]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
ones

array([[1, 1],
       [1, 1]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
rng = np.random.default_rng() 

In [ ]:
rng.random(3) 

array([0.3611222 , 0.18683089, 0.90291969])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rng.random((3, 2)) 

array([[0.33888846, 0.37190545],
       [0.33231637, 0.43230143],
       [0.30244148, 0.27413257]])

In [ ]:
rng

Generator(PCG64) at 0x1998E9F5AC0

In [ ]:
rng.integers(5, size=(2, 4)) 

array([[4, 4, 0, 0],
       [4, 2, 1, 0]], dtype=int64)

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
unique_values = np.unique(a)

In [ ]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)

In [ ]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
unique_values, occurrenced_count = np.unique(a, return_counts=True)

In [ ]:
print(occurrenced_count)

[3 2 2 2 1 1 1 1 1 1]


In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
unique_values = np.unique(a_2d)

In [ ]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
unique_rows = np.unique(a_2d, axis=0)

In [ ]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [ ]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(indices)

[0 1 2]


In [ ]:
print(occurrence_count)

[2 1 1]


In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)

In [ ]:
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
reversed_arr = np.flip(arr_2d)

In [ ]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [ ]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [ ]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])

In [ ]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [ ]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()

In [ ]:
a1[0] = 99

In [ ]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = x.ravel()

In [ ]:
a2[0] = 98

In [ ]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import re

In [ ]:
 data = """
 park 800905-1049118
 kim 700905-1059119
 """
    
pat = re.compile("(\d{6})[-]\d{7}")
print(pat.sub("\g<1>-*******", data))  #g:gruop


park 800905-*******
kim 700905-*******



In [ ]:
#NLTK : 자연어 처리를 위한 Tool kit

In [ ]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import nltk

In [ ]:
#nltk.download()

In [ ]:
from nltk.book import *

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [ ]:
import re
wordlist = [w for w in nltk.corpus.words.words('en') if w.islower()]  #소문자만 

In [ ]:
len(wordlist)

210687

In [ ]:
[w for w in wordlist if re.search('ed$',w)]

['abaissed',
 'abandoned',
 'abased',
 'abashed',
 'abatised',
 'abed',
 'aborted',
 'abridged',
 'abscessed',
 'absconded',
 'absorbed',
 'abstracted',
 'abstricted',
 'accelerated',
 'accepted',
 'accidented',
 'accoladed',
 'accolated',
 'accomplished',
 'accosted',
 'accredited',
 'accursed',
 'accused',
 'accustomed',
 'acetated',
 'acheweed',
 'aciculated',
 'aciliated',
 'acknowledged',
 'acorned',
 'acquainted',
 'acquired',
 'acquisited',
 'acred',
 'aculeated',
 'addebted',
 'added',
 'addicted',
 'addlebrained',
 'addleheaded',
 'addlepated',
 'addorsed',
 'adempted',
 'adfected',
 'adjoined',
 'admired',
 'admitted',
 'adnexed',
 'adopted',
 'adossed',
 'adreamed',
 'adscripted',
 'aduncated',
 'advanced',
 'advised',
 'aeried',
 'aethered',
 'afeared',
 'affected',
 'affectioned',
 'affined',
 'afflicted',
 'affricated',
 'affrighted',
 'affronted',
 'aforenamed',
 'afterfeed',
 'aftershafted',
 'afterthoughted',
 'afterwitted',
 'agazed',
 'aged',
 'agglomerated',
 'aggri

In [ ]:
[w for w in wordlist if re.search('^..j..t..$',w)]

['abjectly',
 'adjuster',
 'dejected',
 'dejectly',
 'injector',
 'majestic',
 'objectee',
 'objector',
 'rejecter',
 'rejector',
 'unjilted',
 'unjolted',
 'unjustly']

In [ ]:
[w for w in wordlist if re.search('^[ghi][mno][jlk][def]$',w)]

['gold', 'golf', 'hold', 'hole']

In [ ]:
chat_words = sorted(set(w for w in nltk.corpus.nps_chat.words()))

In [ ]:
[w for w in chat_words if re.search('^m+i+n+e+$',w)]

['miiiiiiiiiiiiinnnnnnnnnnneeeeeeeeee',
 'miiiiiinnnnnnnnnneeeeeeee',
 'mine',
 'mmmmmmmmiiiiiiiiinnnnnnnnneeeeeeee']

In [ ]:
[w for w in chat_words if re.search('^[ha]+$',w)]

['a',
 'aaaaaaaaaaaaaaaaa',
 'aaahhhh',
 'ah',
 'ahah',
 'ahahah',
 'ahh',
 'ahhahahaha',
 'ahhh',
 'ahhhh',
 'ahhhhhh',
 'ahhhhhhhhhhhhhh',
 'h',
 'ha',
 'haaa',
 'hah',
 'haha',
 'hahaaa',
 'hahah',
 'hahaha',
 'hahahaa',
 'hahahah',
 'hahahaha',
 'hahahahaaa',
 'hahahahahaha',
 'hahahahahahaha',
 'hahahahahahahahahahahahahahahaha',
 'hahahhahah',
 'hahhahahaha']

In [ ]:
wsj=sorted(set(nltk.corpus.treebank.words()))

In [ ]:
[w for w in wsj if re.search('^[0-9]+\.[0-9]+$',w)]  #\.--> 문자 그 자체를 나타냄

['0.0085',
 '0.05',
 '0.1',
 '0.16',
 '0.2',
 '0.25',
 '0.28',
 '0.3',
 '0.4',
 '0.5',
 '0.50',
 '0.54',
 '0.56',
 '0.60',
 '0.7',
 '0.82',
 '0.84',
 '0.9',
 '0.95',
 '0.99',
 '1.01',
 '1.1',
 '1.125',
 '1.14',
 '1.1650',
 '1.17',
 '1.18',
 '1.19',
 '1.2',
 '1.20',
 '1.24',
 '1.25',
 '1.26',
 '1.28',
 '1.35',
 '1.39',
 '1.4',
 '1.457',
 '1.46',
 '1.49',
 '1.5',
 '1.50',
 '1.55',
 '1.56',
 '1.5755',
 '1.5805',
 '1.6',
 '1.61',
 '1.637',
 '1.64',
 '1.65',
 '1.7',
 '1.75',
 '1.76',
 '1.8',
 '1.82',
 '1.8415',
 '1.85',
 '1.8500',
 '1.9',
 '1.916',
 '1.92',
 '10.19',
 '10.2',
 '10.5',
 '107.03',
 '107.9',
 '109.73',
 '11.10',
 '11.5',
 '11.57',
 '11.6',
 '11.72',
 '11.95',
 '112.9',
 '113.2',
 '116.3',
 '116.4',
 '116.7',
 '116.9',
 '118.6',
 '12.09',
 '12.5',
 '12.52',
 '12.68',
 '12.7',
 '12.82',
 '12.97',
 '120.7',
 '1206.26',
 '121.6',
 '126.1',
 '126.15',
 '127.03',
 '129.91',
 '13.1',
 '13.15',
 '13.5',
 '13.50',
 '13.625',
 '13.65',
 '13.73',
 '13.8',
 '13.90',
 '130.6',
 '130.7',
 '

In [ ]:
[w for w in wsj if re.search('^[A-Z]+\$$',w)]

['C$', 'US$']

In [ ]:
[w for w in wsj if re.search('^[0-9]{4}$',w)]

['1614',
 '1637',
 '1787',
 '1901',
 '1903',
 '1917',
 '1925',
 '1929',
 '1933',
 '1934',
 '1948',
 '1953',
 '1955',
 '1956',
 '1961',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1975',
 '1976',
 '1977',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2005',
 '2009',
 '2017',
 '2019',
 '2029',
 '3057',
 '8300']

In [ ]:
[w for w in wsj if re.search('[a-z]{5,}-[a-z]{2,3}-[a-z]{,6}$',w)]   #5개 이상,6개 미만

['black-and-white',
 'bread-and-butter',
 'father-in-law',
 'machine-gun-toting',
 'savings-and-loan']

In [ ]:
[w for w in wsj if re.search('^[0-9]+-[a-z]{3,5}',w)]

['10-day',
 '10-lap',
 '10-year',
 '100-megabyte',
 '100-share',
 '11-month-old',
 '12-member',
 '12-point',
 '12-year',
 '14-hour',
 '15-day',
 '150-point',
 '17-year-old',
 '18-year-old',
 '19-month-old',
 '190-point',
 '20-point',
 '20-stock',
 '21-month',
 '237-seat',
 '240-page',
 '25-year-old',
 '27-year',
 '30-day',
 '30-minute',
 '30-point',
 '30-share',
 '30-year',
 '300-day',
 '31-year-old',
 '36-day',
 '36-minute',
 '36-store',
 '37-year-old',
 '40-megabyte',
 '40-year-old',
 '42-year',
 '43-year-old',
 '50-state',
 '500-stock',
 '51-year-old',
 '52-week',
 '520-lawyer',
 '53-year-old',
 '54-year-old',
 '55-year-old',
 '58-year-old',
 '59-year-old',
 '62-year-old',
 '63-year-old',
 '64-year-old',
 '69-point',
 '75-year-old',
 '84-month',
 '84-year-old',
 '87-store',
 '90-cent-an-hour',
 '90-day']

In [ ]:
a=[w for w in wsj if re.search('(ed|ing)$',w)]   #|--> or

In [ ]:
len(a)

1841

In [ ]:
#http://wikidocs.net/4308